### ISSUE TITLE
Why is your code different from the description in the paper？

### ISSUE THREAD

**Issue by tfzhang006** [xinge008/Cylinder3D#12]
Thank you very much for making this job public, but I have a few questions:
Why is your code different from the description in the paper？
1. Asymmetrical 3D convolution is not used in the decoder part and there are two extra 3x3x3 conv blocks.
2. There is no point refinement module.

**Comment by xinge008** [comment]
@tfzhang006 
1: yes, the extra conv3×3s are used to change the dimension of the low-level features and fused features, respectively. For the upblock, asymmetric convolutions are used, but no residual connection.

2: since the current codebase is the preliminary version, the point refinement is not involved.
