### ISSUE TITLE
validation Iou

### ISSUE THREAD

**Issue by fengjiang5** [xinge008/Cylinder3D#134]
Hello, it's a so exciting work on point cloud segmentation. And I'am try to use it as my backbone, so I have read your paper so many times. But still I have some question about the results on validation.
I see your result on validation is 65.9, and no iou for each class. Can you announce them if possible.
Thanks a lot. Hope for your reply.

**Comment by xinge008** [comment]
![valset_results](https://user-images.githubusercontent.com/53744467/170609413-2d3cfd8f-c9b6-4841-80a3-5cd45bf7eea3.jpg)
The detailed results on valset.

**Comment by fengjiang5** [comment]
Thanks a lot for your reply. Maybe the valid set has few motorcyclist and other-ground.

**Comment by YEOMJINSEOP** [comment]
Thansk for sharing helpful issues.
However, i'm curious why validation results show "bus" instead of "other-vehicle"?
In the cylinder3D paper, there's no "bus" label reported on semanticKITTI dataset.
In config/label_mapping/semantic-kitti.yaml, "bus" is mapped to "other-vehicle"
Could you tell me why "bus" result is shown in this code?
