### ISSUE TITLE
How to train multipleScan experiments on Semantic-KITTI

### ISSUE THREAD

**Issue by Hao-HUST** [xinge008/Cylinder3D#34]
Hi, thanks for sharing your great work!

I have been tested your train.sh to run single-scan experiments on Semantic-KITTI, but how should I run multi-scan experiments?

I notice that you add the multi-scan dataloader code on PC_dataset.py (https://github.com/xinge008/Cylinder3D/blob/6dfbbfa0ea44f1f0196951f139e756cbea5205bb/dataloader/pc_dataset.py#L130). I tried to modify the pc_dataset_type from "SemKITTI_sk" to "SemKITTI_sk_multiscan", but the train.sh failed.

If I hope to train Cyinlder3D on multi-scan LiDAR data, how should I do?

**Comment by xinge008** [comment]
I just release the data processing of multi-scan point clouds; 
To keep the code structure clean and consistent, I do not give more modification. 
Because the network of multi-scan is same with single-frame, some modifications about the input are required. You can follow the error log to make it or you can wait my next update.

**Comment by Hao-HUST** [comment]
OK, thanks. When you plan to release the next update?

**Comment by xinge008** [comment]
No specific plan now. Maybe you can watch the repo and check the notification.
