### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by chenpengxin** [xinge008/Cylinder3D#41]
It takes Quadro GV100  **5 hours** for **1 epoch**.    Anybody trained the model on RTX3090? I failed to compile SpConv lib on 3090.

**Comment by chenpengxin** [comment]
Found it. #32

**Comment by FrancescoMandru** [comment]
Did you solve your issue on compiling with 3090? @chenpengxin

**Comment by lzhnb** [comment]
> Did you solve your issue on compiling with 3090? @chenpengxin

I think the compile errors are caused by high-version pytorch. And the compile errors may be as follow 2 parts (what I met):
1. torch::jit::register... in `src/spconv/all.cc`: In high-version pytorch, the `register` func is not in the `jit` namespace, or the `jit` namespace is deprecated. You just need to modify `torch::jit::register` as `torch::register`. (remove the `jit` namespace).
2. Use the ninja to build, you need to modify `BuildExtension` to `BuildExtension.with_options(use_ninja=False)` in `setup.py`.
